version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - socket_server_1
      - socket_server_2
      - socket_server_3
    networks:
      - nginx-lb-network

  socket_server_1:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    networks:
      - nginx-lb-network

  socket_server_2:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    networks:
      - nginx-lb-network
  socket_server_3:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"
    networks:
      - nginx-lb-network

networks:
  nginx-lb-network:
    driver: bridge
